flyspray/flyspray

lang/.langdiff.php
Current implementation shows all translated strings as untranslated.
=> Fix needed for translations to another languages

setup/upgrade/1.0/upgrade.xml
Seemed to cure the update process for me.
=> Add all new or altered tables to upgrade.xml.

setup/upgrade.php, setup/upgrade/1.0/datadict-postgres.inc.php
It's just here waiting in case the project chooses to distribute it's own version. In that case, the upgrader too needs some additional checks and warnings.
=> This version can handle upgrading of Flyspray.

setup/upgrade/1.0/flyspray-install.xml
Wrong number of columns in SQL query.
=> Fix for issue #82 "Default user not created".

themes/CleanFS/templates/header.tpl
=> Fix logo location.

scripts/index.php
When 'parent' column was added to visible fields in tasklist, I got "Undefined index...". These seems to fix the issue.
=> Fix parent supertask mess

includes/modify.inc.php, setup/upgrade.php, setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml
Detects the situation and even corrects the database. Table list_category needs another solution. Additional checks into includes/modify.inc.php will be added in a later pull request.
=> Fix for issue #102

includes/class.effort.php, themes/CleanFS/templates/pm.prefs.tpl
Note that the numbering of formats changed. Do we still need more?
=> Effort tracking fix and additional formats.

scripts/toplevel.php, themes/CleanFS/templates/toplevel.tpl
When viewing 'all projects' and project = 0.
=> Fix 'undefined index' for toplevel view

includes/class.tpl.php
avatarllink: replaced float and padding by more generic class and style
=> fix avatar html, class and style

themes/CleanFS/theme.css
.. and saving some Bytes in theme.css
=> paving the way for comment display overhaul

includes/modify.inc.php, lang/en.php
TODO: Check that necessary event logging categories do exist and add event logging.
=> A few sanity checks for sub/parent tasks.

setup/upgrade/1.0/flyspray-install.xml
I didn't check if rightmost values in group permissions are actually right ones, just removed one extra value.
=> Fixed install once again.

themes/CleanFS/templates/admin.prefs.tpl, themes/CleanFS/templates/common.profile.tpl
=> Display logo in the admin panel

includes/class.backend.php, includes/events.inc.php, includes/modify.inc.php
These two were unfinished business in the existing code base. The rest will probably remain as TODO notes in version 1.0.
=> Implemented two events.

includes/class.flyspray.php, includes/class.project.php, includes/class.user.php, lang/en.php, scripts/details.php, setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml, themes/CleanFS/templates/common.editgroup.tpl, themes/CleanFS/templates/common.newgroup.tpl, themes/CleanFS/templates/details.view.tpl
Already somewhat tested. It's coming in a bit late, but both I and Jordan have a real use case for it, so think really carefully before rejecting...
=> View task permissions

header.php, setup/composerit.php, setup/composerit.pl, setup/composerit2.pl, setup/composertest.php, setup/index.php, setup/lang/de.php, setup/lang/en.php
If some circumstances matched, required libraries can be installed by composer from browser interface without needing shell access to the server.
=> composer install hack

includes/class.tpl.php, themes/CleanFS/templates/details.view.tpl, themes/CleanFS/templates/header.tpl
+ some additional small things I found.
=> Remove unnecessary vertical white space from view task

includes/modify.inc.php, themes/CleanFS/templates/details.view.tpl
There's probably some more still lurking around somewhere...
=> Get rid of a few remaining "missingtoken" messages.

htaccess.dist, includes/modify.inc.php
=> Security for SetEnv

includes/class.notify.php
i change directly to master, will revert my pull requests from install-hack branch.
=> send text and html in one mail

includes/class.flyspray.php
based on provided patch for 0.9.9.7 on bugs.flyspray.org, modified for 1.0.
Untested, works only as stub for later dev.
=> add ldap patch

includes/class.backend.php, includes/class.flyspray.php, includes/modify.inc.php, themes/CleanFS/templates/admin.userrequest.tpl
Next thing to do: check that the email is really sent and that accept/deny buttons work.
=> No admin request was made for an account created as disabled.

setup/exportdb.php
Update currently unused  file reviewed
=> exportdb.php fixes

themes/CleanFS/templates/pm.pendingreq.tpl
Hope this does not require url-rewriting work also. And I really should learn some day how to use styling and make those buttons look reasonable.
=> Make accepting re-open request work.

themes/CleanFS/templates/details.view.tpl, themes/CleanFS/theme.css
And that entire quick edit is a CHAOS with those HUGE buttons for blind
people
=> Forgot make public

includes/class.backend.php, includes/class.project.php, includes/modify.inc.php, index.php, scripts/reports.php, setup/upgrade/1.0/flyspray-install.xml, themes/CleanFS/templates/editcomment.tpl
More probably coming later. @danoh, you've got a real db with lots of data, could you check if there's any real improvement.
=> Small database related enhancements and fixes

Tests/CreateTestData.php
While the theme keeps waiting on being finished, I decided instead to have a few beers, a little bit of wine, have fun and program slightly drunken. This actually works, although it's still far from finished work. Hope you enjoy it as much as myself.
=> Just sketching how to create a lot of data for stress testing.

Tests/CreateTestData.php
Works now with mysql too, I hope.
=> Portability fixes and now adds more data.

includes/class.flyspray.php, includes/class.tpl.php, themes/CleanFS/templates/footer.tpl
Avatars were broken when using url_rewriting
=> Fix avatars and removed svn

themes/CleanFS/templates/details.tabs.comment.tpl, themes/CleanFS/templates/editcomment.tpl, themes/CleanFS/theme.css
=> Edit comment

themes/CleanFS/templates/details.tabs.comment.tpl, themes/CleanFS/templates/editcomment.tpl, themes/CleanFS/theme.css
=> Bringing comment preview back

themes/CleanFS/templates/details.tabs.comment.tpl, themes/CleanFS/templates/editcomment.tpl, themes/CleanFS/theme.css
For now at least. For complete rewrite wait FS1.1, it will need some
jquery for interactive box. The lastpoint for FS1.0 are those crap
buttons
=> Should complete Github like comments

header.php, setup/cleanupaftersetup.php, setup/composerit.php
Please test if its working for you and give feedback if not with error dump/screenshots.
=> composerit

.travis.yml
just adding composer requirements to make more realistic testing possible.
=> adding composer requirements for travis-ci testing

includes/class.tpl.php
Let the browser decide the protocol
=> Peterdd is correct

themes/CleanFS/templates/common.profile.tpl
=> Commenting out pre implement

lang/fr.php
And that point 3.... I'm not even sure it means anything in english, so
I changed it to something that means something in french...
=> Wow, needed cleanup

themes/CleanFS/theme.css
for task details view and list mouseover task description
=> simple css for content html tables

themes/CleanFS/templates/admin.groups.tpl
Thank you for the cool work peterdd. Just made it look a bit less messy...
=> Bit better looking admin groups

includes/class.backend.php, includes/class.user.php
And one already existing one too.
=> Fixed a few bugs with new view permissions

includes/class.backend.php
Should finally bring $forbidden_tasks_count to 0. Unlike previous version (I didn't make even a pull request), this one has been tested both with mysql (5.6.24) and postgresql (9.4.1). No  complaints back.
@peterdd, check this you too as soon as you can. I think I got it exactly right this time and there's been quite a lot of tuning to make it reasonable fast. But there's no way make it really fly if there are tens of thousands open tasks...
=> Rights check in sql

includes/class.backend.php
Faster at getting wrong results and in one case causing sql syntax error is not the way to go.
=> Reverting this change.

htaccess.dist
because this is not allowed/supported in some hosting / server setups.
=> template for forcing TLS/SSL and disabled the SetEnv lines

themes/CleanFS/templates/loginbox.tpl, themes/CleanFS/theme.css
oauth class is used on body tag for ?do=oauth
=> remove css class oauth double usage

setup/templates/structure.tpl
even if the targets aren't very helpful at the moment better then leading to a 404 error ...
=> fixing external links in setup

themes/CleanFS/templates/index.tpl
=> change font icon depending on search form status

includes/class.user.php, js/callbacks/deletesearches.php, js/callbacks/getpreview.php, js/callbacks/getsearches.php, js/callbacks/quickedit.php, js/callbacks/searchnames.php, js/callbacks/usersearch.php, js/functions.js, themes/CleanFS/templates/details.view.tpl, themes/CleanFS/templates/index.tpl, themes/CleanFS/templates/links.searches.tpl
Quite big patch. Please review and test.
Fix for FS#2006
=> anti csrf token checks for data changing ajax requests

scripts/langdiff.php, themes/CleanFS/templates/common.cat.tpl, themes/CleanFS/templates/common.list.tpl, themes/CleanFS/templates/pm.os.tpl, themes/CleanFS/templates/pm.resolution.tpl, themes/CleanFS/templates/pm.status.tpl, themes/CleanFS/templates/pm.tasktype.tpl, themes/CleanFS/templates/pm.version.tpl, themes/CleanFS/theme.css
By showing global list settings there.
Further:
- small fix for translations overview page
- fix for empty cat listing
=> enhance project management settings

setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml, themes/CleanFS/templates/common.cat.tpl, themes/CleanFS/templates/common.list.tpl, themes/CleanFS/templates/links.tpl, themes/CleanFS/theme.css
- more css fixes on admin and project pages
- fixes for switching between admin and project pages.
=> category_name varchar(40) and

scripts/details.php, themes/CleanFS/templates/details.view.tpl, themes/CleanFS/theme.css
At least make tag styling possible.
Even it is not yet clear whats the purpose of adding tags to flyspray should be nor the management for tags exists yet (editing tag names, add and remove tags from tasks, deleting tags, searching and filtering by tags, listing of tags by projects, grouping tags, adding colors or styles to tags, translation of tags, select from lists or autocompletion for adding tags, help hint for tags...)
Should it be an additional freestyle tagging like hash tags on twitter or an alternative to group tasks or add properties to tasks without custom fields, or ..?
=> tag styling

scripts/admin.php, scripts/pm.php, themes/CleanFS/templates/admin.menu.tpl, themes/CleanFS/templates/admin.tags.tpl, themes/CleanFS/templates/pm.menu.tpl, themes/CleanFS/templates/pm.tags.tpl
At least give users info that tags feature isn't fully implemented yet and that there is no management or cool functionality yet.
They can only be added on task creation and be shown on task details view at the moment.
=> stub for tag management

themes/CleanFS/templates/header.tpl, themes/CleanFS/templates/links.tpl
=> use $do instead of urlparams

themes/CleanFS/templates/newmultitasks.tpl
but needs still more work for responsible layout...
=> fix newmultitasks

themes/CleanFS/templates/header.tpl
ok, lets start testing on real phone devices..
=> add meta viewport

scripts/index.php
not a final solution..
html construction here is not the right way. Rework can be done in later Flyspray versions, not FS1.0.
=> quick fix icon for attachments column

scripts/pm.php, themes/CleanFS/templates/pm.groups.tpl, themes/CleanFS/templates/pm.menu.tpl
a bit rough yet.
just merge it pls, will make it a bit nicer next days.
=> pm user groups page

themes/CleanFS/templates/admin.prefs.tpl, themes/CleanFS/templates/pm.prefs.tpl
=> option to show project name on all project task list again

includes/class.notify.php
push as fast as possible, currently gives php error.
Reminds me of adding an automatic php code check for travis-ci on each commit.
=> fix brackets in class.notify.php

includes/class.notify.php, includes/events.inc.php, js/callbacks/quickedit.php
Use common functionality both in includes/class.notify.php and js/callbacks/quickedit.php to detect what changed and how to format it for notifications. Also formatting change for one event in task history.
=> Fix for FS#2015

themes/CleanFS/templates/pm.groups.tpl
forgot to make the pull request lol
=> project param for edit group

scripts/index.php, themes/CleanFS/templates/index.tpl
and moved script out of table to top.
=> tasklist: smaller fa-icons and colgroup

includes/class.tpl.php
Seems safe. A must for comments.
=> Add code to allowed tags.

themes/CleanFS/theme.css
for example code rendered as pre by dokuwiki.
=> scrollbars for overlong pre in comments

themes/CleanFS/templates/details.tabs.remind.tpl
and font icon for toggle (could be nicer formatted, later...)
=> fix table structure on reminder tab

themes/CleanFS/templates/details.tabs.remind.tpl
which still looks a bit better than fa-exchange.
=> that a-tag still has the icon by toggle_selected

js/jscalendar/lang/calendar-fi.js
We should also consider updating the calendar component. It seems to be 10 year old...
=> Missing translations prevent the calendar working.

includes/class.notify.php, schedule.php
=> Peters fix and added version check.

themes/CleanFS/theme.css
and make at least the task details page readable on smallest mobile size (320 width phones)
=> let the tags float on same row as the task title

lang/de.php, lang/en.php, themes/CleanFS/templates/newtask.tpl
tooltip on create task for the limited implementation of free tagging in flyspray.
=> tagsinfo translation

themes/CleanFS/theme.css
or a click on the vote count pops under the comments...
Can be seen if there are many votes on a task and comments exists.
e.g.https://bugs.flyspray.org/index.php?do=details&task_id=407&project=1
(unless upgraded after this and css reloaded.. ;-))
=> css #taskdetails #showvotes needs positive z-index

setup/upgrade.php, setup/upgrade/1.0/upgrade.xml
=> Moved two db updates to upgrade.xml now it is possible.

themes/CleanFS/templates/details.tabs.comment.tpl, themes/CleanFS/theme.css
@psycho If you are ok with it do the merge.
Else we can discuss it.
=> only one icon webfont

includes/class.project.php, themes/CleanFS/templates/admin.tags.tpl, themes/CleanFS/templates/pm.tags.tpl
noncritical stuff that can be used for old tag feature and tag feature rewrite.
(I had merge conflicts with my tagrewrite and don't know whats the problem is for github, so try to make code differences between old and new tag feature as small as possible and do things that can be done for both variants)
=> Tags codesharingoldandnew

htaccess.dist, includes/modify.inc.php
@psycho Please review this.
I made my required changes for my environments, so the activation in the admin area is working for me.
=> start url rewriting review FS#1963

includes/class.notify.php, includes/class.project.php
And another small fix. Did I really forget to make a pull request yesterday?
=> Use standard SQL, not MySQL dialect.

includes/class.backend.php, scripts/index.php
for mysql using group_concat.
others fallback to "oneassigneename, +n"
=> show all assignees in task list

includes/class.database.php
Only variables should be passed by reference PHP >=5.0
=> PHP Strict Standards:  Only variables should be passed by reference

includes/class.tpl.php
Improved old pattern for URLs matching
=> Change URLs into hyperlinks

lang/fr.php
=> Little orthographic update

includes/class.flyspray.php
Fix a PHP Notice:  Use of undefined constant method - assumed 'method'
=> Add forgotten $

themes/CleanFS/templates/admin.prefs.tpl
- Add missing attributes for default_order_by and default_order_by_dir
- Fix showjabberppass with showjabberpass
- Add class *labeltextarea* to the columns and fields labels
=> Add missing attributes "for" + class labeltextarea + Fix

themes/CleanFS/templates/admin.newproject.tpl
=> Fix a missing underscore

includes/class.tpl.php
Related to github pull #433, rewrite of the patch with no impact on other cases
=> Fix reports URL in non rewrite mode

themes/CleanFS/templates/newtask.tpl
Related to #439
- add project_id in query params for callbacks/searchtask.php
=> add project_id in query params

setup/index.php, setup/lang/en.php, setup/templates/database.tpl
=> create mysql database always utf8

themes/CleanFS/templates/index.tpl, themes/CleanFS/theme.css
and some template and css cleanup
=> enable closed task row styling

scripts/langdiff.php, scripts/langedit.php
=> small work on builtin translator

themes/CleanFS/templates/details.view.tpl
Here is a little update related to the previous css pull.
=> Update tag class name

includes/class.backend.php, includes/class.project.php, themes/CleanFS/templates/admin.prefs.tpl
=> second sort for globals tasklist

includes/modify.inc.php, themes/CleanFS/templates/common.list.tpl
Interface not finished yet, but now you can add predefined classes to tags in admin and project setting area for styling.
=> Tag classes

js/callbacks/quickedit.php, themes/CleanFS/templates/details.view.tpl
security fix: authenticated users with edittask permission for the current task (and some hacking knowledge) were able to set invalid values for the current task.
=> quickedit fixes

lang/de.php, lang/en.php, themes/CleanFS/templates/admin.prefs.tpl, themes/CleanFS/templates/shortcuts.tpl
- Test-Mail-Part in Email-Settings from Admin-Area now translated
- Keyboard-Shortcut-Link now translated
- Correct german translations added
=> Added some language-entries with german translation

scripts/details.php
Notice: Undefined variable: move in scripts/details.php on line 64
GET /index.php?do=details&task_id=1&edit=yep
=> Fix a notice

lang/de.php, lang/en.php, themes/CleanFS/templates/shortcuts.tpl
=> Shortcut-Window languagify

js/callbacks/savesearches.php
=> Clean unused code

includes/class.tpl.php, themes/CleanFS/templates/profile.tpl
=> consistent links to user pages

includes/i18n.inc.php
Please see [FS#2106](https://bugs.flyspray.org/index.php?do=details&task_id=2106)
=> fix local language

lang/pl.php
Hey polish guys, 
please check if my assumption is correct and give feedback.
=> polish locale

includes/i18n.inc.php, setup/index.php
- support local language when install
- replace hardcoded english with translation strings in code files
=> Installer i18n part two

header.php
alternative to pull request 550
This patch is for all quickedit calls, not limited to estimated_effort.
=> load project properties for quickedit checks early

htaccess.dist
The multi-task-view can now accessed again
=> Another little fix in url_rewriting

includes/class.user.php, index.php, scripts/index.php, scripts/toplevel.php, themes/CleanFS/templates/index.tpl, themes/CleanFS/templates/links.tpl, themes/CleanFS/templates/toplevel.tpl
adds a new function can_select_project() and required to change checks at several places.
=> bugfix FS#2120 anon task creation

plugins/dokuwiki/inc/parser/parser.php
=> Fix PHP7-issues in dokuwiki

lang/fr.php
I just add some translations in French, I think it's ok.
=> Update french language

.travis.yml
- Container based infrastructure for faster startup see https://docs.travis-ci.com/user/workers/container-based-infrastructure/
- Caching composer for speed up tests (less freeze tests) see https://docs.travis-ci.com/user/caching/
=> Add container-based infrastructure and composer caching

includes/modify.inc.php
start work on FS#2135, checks for users with task edit permission, but not admin perms.
=> add sub/parent check, new FIXME notes

includes/modify.inc.php
=> fix FS#2135

includes/modify.inc.php, themes/CleanFS/templates/common.profile.tpl, themes/CleanFS/templates/profile.tpl
this param is a group id, not a project id
=> Fix oldgroupparam

includes/class.flyspray.php, setup/upgrade/1.0/upgrade.xml
Now it's possible to use secure password-hashes.
=> Added SHA512-Algorithm for secure passwords

includes/class.flyspray.php
- A simple Calculate Only Once optimization
- Usage of single quote
=> Optimization of cryptPassword method

js/jscalendar/lang/calendar-el.js
A couple of new strings and proofreading
=> Calendar translation (el)

composer.json, phpunit_mysql.xml, phpunit_pgsql.xml
- It increases tests speed with less CPU/RAM usage
- It's a better overview of what is covered
=> Exclude vendor from code coverage

schedule.php
=> Reuse $now + clean unused code

composer.json, phpunit_mysql.xml, phpunit_pgsql.xml
#598 As a first try to fix segmentation fault / zend_mm_heap corrupted
=> Remove PHPUnit 4.8

themes/CleanFS/templates/index.tpl
=> Restrict details descbox hover on task list to summary column.

includes/class.tpl.php, themes/CleanFS/theme.css
If a user is in the "assigned-to"-list, his avatar displayed smaller than other avatars. This commit repair a malfunction in the avatar-cache.
=> Bugfix in displaying avatars

js/functions.js
The following functions are no longer used:
- adduserselect
- setUpSearchBox
- toggleSearchBox
=> Remove some dead JS code

includes/modify.inc.php
- Usage of GPC post method
- Remove unnecessary else + move OK comment for clarity purpose
=> Replace direct access to input var by using a GPC method

README.md
- Fix PHP install. @todo To replace by php7 in the near future
- F5 / CTRL+F5 @see http://stackoverflow.com/questions/385367/what-requests-do-browsers-f5-and-ctrl-f5-refreshes-generate, depending on which component is managing the cache (browser, proxy, server)
=> Fix install typos

index.php, themes/CleanFS/templates/common.attachments.tpl
for the download image button of task attachments.
=> force download of images

includes/class.database.php
rough enable setting pdo_mysql as dbtype in flyspray.conf.php
experimental! dont use it for real Flyspray. used only for evaluation of adodbs other dbdrivers and testing.
=> adodb 'pdo_mysql'

setup/index.php
and using ADONewConnection instead of alias NewADOConnection to be consistent with the other flyspray sources.
=> fix php7 notices at setup

.htaccess, composer.json, scripts/register.php, securimage.php, vendor/.htaccess
Trying to eleminate current and future potential weaknesses of 3rd-party components.
=> deny vendor/ dir

includes/class.flyspray.php
get rid of one deprecated create_function() notice for php7.2
=> deprecated create_function since PHP7.2

setup/index.php
=> FIX: Typo in one of microsoft's config var

lang/en.php, lang/it.php
As per email conversation, i added this new key to the default (EN) translation
=> Added new key tooltipshorttasktitle in default EN file

includes/modify.inc.php
make sure only array of userids is accepted and not accidently disable or delete own admin account
=> validation for editallusers form

includes/modify.inc.php, index.php, plugins/dokuwiki/inc/geshi.php
A couple of calls to `create_function`, deprecated in PHP7.2
=> Three straggling `create_function` calls

feed.php, header.php, includes/class.database.php, includes/class.effort.php, includes/class.flyspray.php, includes/class.jabber2.php, includes/class.notify.php, includes/class.project.php, includes/class.tpl.php, includes/class.user.php, includes/events.inc.php, includes/modify.inc.php, index.php, schedule.php
for better readability and consistency. functions are case-insensitive in php btw.
=> Start functions lowercase

js/callbacks/checkrelated.php, js/callbacks/checksave.php, js/callbacks/deletesearches.php, js/callbacks/quickedit.php, js/callbacks/searchnames.php, js/callbacks/searchtask.php, js/callbacks/testemail.php, js/callbacks/usersearch.php, scripts/admin.php, scripts/authenticate.php, scripts/depends.php, scripts/details.php, scripts/editcomment.php, scripts/index.php, scripts/lostpw.php, scripts/myprofile.php, scripts/newtask.php, scripts/oauth.php, scripts/pm.php, scripts/register.php, scripts/reports.php, scripts/roadmap.php, scripts/toplevel.php, scripts/user.php
in files within scripts/ and js/callbacks to improve readability and consistency
=> lowercase firstchar of function calls

scripts/admin.php, themes/CleanFS/templates/admin.checks.tpl
first step in improving quality of existing old user password hashes - report stats in admin area and give suggestions
=> Info bad hashes

scripts/authenticate.php, setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml
timestamp when a user last logins (by username/password or oauth)
=> add last_login user field

includes/class.flyspray.php, includes/fix.inc.php, includes/modify.inc.php, scripts/authenticate.php
during login when user provided password
=> Upgrade pwhashes if possible

lang/it.php
Also, slightly revised massopsdisabled message
=> Updated with massopsenable and lastlogin strings

includes/class.backend.php, includes/constants.inc.php
to replace hardcoded int 6 in source with a meaningful constant
=> RESOLUTION_DUPLICATE

themes/CleanFS/templates/common.list.tpl, themes/CleanFS/theme.css
as preparation for merge properties feature FS#1791
=> one table for global/project common.list.tpl

js/callbacks/deletesearches.php, js/callbacks/quickedit.php, js/callbacks/savesearches.php, js/callbacks/testemail.php
so they appear in web server logs and browser webdevtools as intended, not as error 500 status codes
=> fix response http status codes for some ajax request 

themes/CleanFS/templates/index.tpl, themes/CleanFS/theme.css
assuming the tasklist export is a seldom used feature, move it to the right top edge of the task search form.
=> smaller tasklist export button

scripts/langdiff.php
- Did some polish to make code more readable and coherent with the rest of the sources (at least the majority of them :D)
- Changed "Translate en" to "Edit en" because it seems more logical and correct given that English is the base reference
- A couple of fixes
=> Some polish and small corrections

includes/class.flyspray.php, themes/CleanFS/templates/shortcuts.tpl, themes/CleanFS/theme.css
to enable to show the user the key combination that works on his system
=> detect basic browser and platform at session start

README.md
=> Update README to current rc9 version

README.md
Just to have standardized writing inside the same sentence
=> Standardize writing

themes/CleanFS/templates/details.view.tpl, themes/CleanFS/templates/myprofile.tpl, themes/CleanFS/theme.css
but not the others task fields in a task table view (as their values are usually not by set by funny guys trying to break a layout)
=> wrap summary string if necessary

includes/class.backend.php
Makes the search field also look in the tag table for searched string.
=> feat: search in tags

scripts/admin.php, themes/CleanFS/templates/admin.checks.tpl
and show also collation and character set for postgresql
=> db connection info on admin checks page

themes/CleanFS/darkmode.css, themes/CleanFS/templates/admin.checks.tpl, themes/CleanFS/theme.css
just moved CSS coloring from template file to the CSS files
=> dbtable color darkmode

lang/it.php
Updated "tooltipshorttasktitle" and "lastlogin"
=> Updated new strings

includes/class.flyspray.php, scripts/admin.php, themes/CleanFS/templates/common.editallusers.tpl
started with a simple filter setting, will add more filters if required
=> filter of userlist by enabled/disabled users

themes/CleanFS/templates/admin.prefs.tpl, themes/CleanFS/templates/pm.prefs.tpl
when a second sort parameter for task list is not yet stored in db
=> fix few php7.4 notices

includes/class.flyspray.php
* fix PHP warning when ini-settings memory_limit, post_max_size or upload_max_filesize are returned as integer by ini_get()
* only do calculation for max_file_size when file_uploads are allowed by php configuration
* formatting of Flyspray::__construct() and class variables
=> fix php7.4 warning when php.ini value is int not string

includes/class.backend.php, includes/class.flyspray.php, includes/class.tpl.php, includes/modify.inc.php, themes/CleanFS/templates/common.list.tpl, themes/CleanFS/templates/details.view.tpl, themes/CleanFS/theme.css
This meant also keep track which tag was added and removed and unchanged when editing a task. Before it was just remove all, add again.
=> show who and when a tag was added to task

mytimers.php, setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml, themes/CleanFS/templates/details.tabs.efforttracking.tpl
adds an database field for optional description of effort entries. This allows describing more granular for what time is spent on a task as requested by FS#2609
=> effort description

scripts/details.php, themes/CleanFS/templates/details.edit.tpl
shows a simple cloud of available tags when editing a task and the use_tags configuration is set for the project of the task.
=> simple tag helper when editing task

plugins/dokuwiki/conf/dokuwiki.php, plugins/dokuwiki/inc/io.php
as it also also removed in original Dokuwiki sources and we do not need it.
Fixes a few warnings in server log.
=> Remove dokuwiki safemodehack

attachments/.htaccess, htaccess.dist, plugins/dokuwiki/conf/.htaccess
There were still some locations that not handled the changed syntax between Apache2.2 to Apache2.4
=> Adapt .htaccess for Apache2.4

js/index.js, scripts/index.php, themes/CleanFS/templates/index.tpl
Over the years more an more possible search parameter were added to Flyspray's task search.
As Flyspray keeps search parameters as query string in the URL for easier bookmarking, it becomes more required to shorten the URL by removing default search parameter values from the query string.
=> Shorter searchurls

js/index.js
when all projects are hidden from guests there is no search form.
=> search input field not always present

plugins/dokuwiki/lib/plugins/changelinks/syntax.php, plugins/dokuwiki/lib/plugins/fslink/syntax.php, plugins/dokuwiki/lib/plugins/newline/syntax.php, setup/index.php
=> more email address cleanup

includes/modify.inc.php
fixes a regression in 1.0-rc11 due Post::val() not intended to work on arrays anymore.
=> delete reminder regression fix

includes/class.recaptcha.php
PHP8 whines when verify() is called static but function is not defined as static...
=> PHP8 static recaptcha::verify()

js/callbacks/getpreview.php
=> load translations also in getpreview.php

includes/class.flyspray.php
Postgresql is not as tolerant as mysql, so aggregate function needed to be accepted
=> userstats query with filter for Postgresql

includes/class.notify.php
finds also urls like https://example.com/?s[]=1&amp;s[]=2
=> find also urls containing [ or ] or ; for notification emails
