scripts/details.php, themes/CleanFS/templates/details.view.tpl
Fixes non-existing index when showing the project name of a dependent or subtask. The original submitter of this feature seems to have misunderstood how $projects array is indexed. There could be alternative solutions to the problem, but I didn't see them immediately. Modifying the SQL-queries and having the necessary information available in $dependency and $subtask seems both safe and working solution.
=> Fix project name in dependent/subtasks.

setup/upgrade.php
Saves a lot of clicking checkboxes after upgrade.
=> Update existing projects to default field visibility.

includes/class.project.php, includes/class.user.php
MySQL doesn't require these, PostgreSQL really does, but they should neither harm MySQL (please test!). It's unknown to me which one of the available event_dates MySQL chooses when it's not explicitly specified, using MIN() seemed safe, because it actually doesn't seem to matter as long as event_date falls on the right date.
=> Add aggregate functions to 2 SQL-queries.

includes/modify.inc.php, lang/en.php, themes/CleanFS/templates/details.view.tpl
- Removed accidentally duplicated "This task blocks these from closing".
- Enhanced error messages.
- Added duplicate checks for category entries too.
Note that when fixing possibly already existing duplicate entries, like having "Report 1" twice on the same level and under same category, the fixing must be done in 2 phases.
First phase:
Report 1 -> Report 1 (rename back later)
Report 1 -> Report 2
Second phase:
Report 1 (rename back later) -> Report 1
Reason: if the first Report 1 is not renamed in the first phase, the second Report 1 has not been yet updated to a new value when first one is checked for duplicates and so will be considered a duplicate entry.
=> Misc small fixes

themes/CleanFS/templates/details.view.tpl
If someone enters unbalanced HTML tags into task description, whole page gets broken.
=> don't put unescaped HTML into page, it breaks the javascript popup.

scripts/index.php, themes/CleanFS/templates/admin.prefs.tpl, themes/CleanFS/templates/pm.prefs.tpl
Prevent "Undefined index: whatevervalue in scripts\index.php on line 229" ever occuring once more and wrote a long explanation about what's really happening, so nobody's going cause the same kind of mess again.
=> Prevent "Undefined index: whatevervalue in scripts\index.php on line 229"

includes/class.tpl.php
when posting data, not for letters used for writing ordinary text. Breaks some searches.
=> Only use html entities for those 5 well-known characters

includes/class.tpl.php
I'm quite sure 
<h1> tag
shouldn't be allowed because this is at least reserved for the task title and there is also a h1-tag on the flyspray website...
Maybe also disallow h2-tag ?
So 
h1 = website heading
h2 = a task heading
h3,h4,h5,h6 = custom headings allowed in the task description
=> allow some more html tags that should be ok

includes/class.notify.php
Reasoning: able to show a small popup with just one-liners briefly telling what happened, or however peter wants to see the notifications, and maybe later in 1.1, also implement more full-featured descriptions on a separate page. Can't be done for 1.0. anymore, too much work.
=> Change field where to store online notification.

includes/modify.inc.php
Storing jabber_id as '0' instead of '' doesn't play nice with notifications.
=> Storing jabber_id as '' instead of '0' if not given.

includes/modify.inc.php, index.php
the register.ok.tpl template should be set at page content position, not output itself before page headings.
=> fix register output

themes/CleanFS/templates/reports.tpl
The reason was a javascript loaded on this page, that autolinks to the task of the clicked row. well on user  account related events there is not task id..
I think this script can be replaced by html only.
But for this bugfix we simply change the id of the eventlog html table.
=> fix FS#1841

themes/CleanFS/templates/links.tpl
The second button for the task search is optional even for the jsless peoples, but made them visible for them.
Think of touch displays...
Hope psycho can live with that.
Without the buttons for jsenabled users the select and quick task search fields now looks like one form, but they are completely different forms ...
=> submit button for the jsless peoples

setup/composerit2.php
This is still an open question if php is not in the path when calling shell_exec
And the php on the commandline should be nearly the same version as the php the web server uses.
for example apache uses mod_php, but for shell_exec we need an executable.
All that is in status "researching" ..
And I know, its all a hack to enable the installation over web browser...
=> php executable for shell_exec

includes/modify.inc.php
Still showing wrong value for those disabled fields when editing, but at least saving works and does not modify the original value.
=> Fix case when user is allowed to edit task, but not all of its fields.

includes/class.tpl.php
the default ckeditor allows to construct html tables, so the table tags shouldn't be stripped here.
=> was a bit too strict on global tag stripping

includes/class.backend.php
It seemed to be using temporary table, which postgresql instead optimized away. Mysql version 5.6.24 btw. And got 50% improvement. No change with postgresql.
=> Faster with mysql.

includes/class.flyspray.php
now any file or directory starting with a '.' is ignored as possible theme directory
fixes warnings from is_file(), is_dir() who are probably bugs in PHP itself.
see for example https://bugs.php.net/bug.php?id=69240
thx to mouts
=> ignore '.' files as directory in listThemes()

setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml
Make db field resolution_name the same size as maxlength in the CleanFS/templates/common.list.tpl
and the other *_name fields from list_*-tables. Because common.list.tpl is currently used also for other db tables, this is the easiest way to fix it.
A bigger solution would be either 
- a template for each list_* table
or
- reading INFORMATION_SCHEMA to get the real field size of the field in the list_* table
=> quick fix FS#1984

setup/upgrade/1.0/flyspray-install.xml, setup/upgrade/1.0/upgrade.xml
see http://php.net/manual/en/function.password-hash.php
They recommend 255 chars, but currently 60 chars is enough.
If we really need one day more than 60 chars we can change that too in later versions easily.
=> resize user_pass field for password_hash() usage

includes/class.project.php
If you call for examples listTaskTypes(true) for different "projects" in one request (like $project1 and $project0 for the global values), 
it returned always only the result of the first query.
I need this to be fixed for working on the field lists of project management pages for FS1.0. Want to show the global list values so project managers don't accidently create duplicate/similiar list field values.
=> use of project id for cache id construction

themes/CleanFS/templates/index.tpl
If it was a user search show table headers too even if there was no result.
If it was just a page view with no tasks as result then even no show a task list table.
Also the checkboxes for mass ops will not shown from now on on system wide task list views because massops are disabled for this kind of views.
=> only show "noresults" string if was a user search

themes/CleanFS/theme.css
I think it looks cleaner and we don't need this line here. There is enough optical separation from the page content because #tasklist or #toolbox have their own border and background.
=> remove border-top line from #footer

themes/CleanFS/templates/common.newgroup.tpl
Probably more then 10-year old artefacts, there is no form action 'newgroup.newgroup' anywhere and it makes no sense.
=> no more false preselected checkboxes on newgroup forms

themes/CleanFS/templates/details.view.tpl
the form tag is visible:block by default , so it wrapped after the vote counter making the +1 button invisible due fixed row height.
so simply make the form there inline...
=> visible +1 vote button again

includes/class.database.php
This is IMHO important for the elimination of some race condition in the flyspray code.
Better use the autoincrement feature to avoid that. Instead of precalculating with an extra sql query. When precalculated, a second db connection could insert between the 2 queries leading to wrong data.
=> add missing Insert_ID() for the db wrapper

includes/class.backend.php, setup/upgrade/1.0/upgrade.xml, themes/CleanFS/templates/index.tpl
This is for all the people who use dokuwiki syntax for flyspray instead of fullhtml/ckeditor.
(including bugs.flyspray.org)
It doesn't solve the issue in dokuwiki of exponential increased render time with growing count of tasks to show (scripts/index.php $perpage var), but the task list view on bugs.flyspray.org should drop from 5 sec (sic!) to nearly nothing (under 100ms for  whole page , tested with flyspray installed on a laptop)
=> Use dokuwikicache for tasklist, fix FS#2021

setup/index.php
PHP5.6 => PHP Fatal error: Non-static method ...::...() cannot be called statically in...
=> Methods called from an incompatible context are deprecated/removed PHP>=5.4

header.php
/header.php has following FIXME mention with "a bit of work" I've done.
```
//FIXME: This is currently a workaround for the fact that parts of the code/templates use i.e. "taskid" and "task_id" for the same thing. This should be fixed cleanly, means a bit of work though.
if      (isset($_GET["task_id"])) $_GET["taskid"]  = $_GET["task_id"];
else if (isset($_GET["taskid"]))  $_GET["task_id"] = $_GET["taskid"];
if      (isset($_POST["task_id"])) $_POST["taskid"]  = $_POST["task_id"];
else if (isset($_POST["taskid"]))  $_POST["task_id"] = $_POST["taskid"];
if      (isset($_REQUEST["task_id"])) $_REQUEST["taskid"]  = $_REQUEST["task_id"];
else if (isset($_REQUEST["taskid"]))  $_REQUEST["task_id"] = $_REQUEST["taskid"];
```
The flow+context for which the workaround is necessary:
`GET …
=> Fix a FIXME mention

themes/CleanFS/templates/details.edit.tpl
/header.php has following FIXME mention with "a bit of work" I've done.
```
//FIXME: This is currently a workaround for the fact that parts of the code/templates use i.e. "taskid" and "task_id" for the same thing. This should be fixed cleanly, means a bit of work though.
if      (isset($_GET["task_id"])) $_GET["taskid"]  = $_GET["task_id"];
else if (isset($_GET["taskid"]))  $_GET["task_id"] = $_GET["taskid"];
if      (isset($_POST["task_id"])) $_POST["taskid"]  = $_POST["task_id"];
else if (isset($_POST["taskid"]))  $_POST["task_id"] = $_POST["taskid"];
if      (isset($_REQUEST["task_id"])) $_REQUEST["taskid"]  = $_REQUEST["task_id"];
else if (isset($_REQUEST["taskid"]))  $_REQUEST["task_id"] = $_REQUEST["taskid"];
```
The flow+context for which the workaround is necessary:
`GET …
=> Rename taskid by task_id

includes/class.flyspray.php, includes/modify.inc.php
Avoids double sending forms by pressing reload button or F5 in browser.
Also seems to fix browser back button issues.
Please test.
fix FS#2057
=> HTTP302 or HTTP303 redirects after POSTs

themes/CleanFS/templates/details.edit.tpl
Some "for" attributes in labels were missing or not related to the right element id.
=> Update/add some label's for and element id

includes/i18n.inc.php
Sometimes $_SERVER['HTTP_ACCEPT_LANGUAGE'] is not set, starting by some bad-coded or quality crawlers to extraordinary browsers.
In these cases, it gives the following PHP notice:
```
Notice: Undefined index: HTTP_ACCEPT_LANGUAGE in includes/i18n.inc.php on line 109
```
=> Fix a PHP Notice

js/callbacks/searchtask.php
/js/callbacks/searchtask.php is called before saving a new task.
A direct call gives the following PHP notice:
```
Notice: Undefined index: detail in /js/callbacks/searchtask.php on line 7
Input Array does not match ?: SELECT count(*) 
FROM `flyspray_tasks` t
WHERE t.item_summary = '%%' AND t.detailed_desc like <br>
Query {SELECT count(*) 
FROM `flyspray_tasks` t
WHERE t.item_summary = ? AND t.detailed_desc like ?} with params {%%} Failed! (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#039;&#039; at line 3)
```
A whitelisting of parameters before the PDO call seems to be more appropriated.
This patch improves 2 aspects:
- Incomplete calls have no information and no sql is used
- It whitelists only …
=> Fix a PHP Notice + PDO call

includes/class.flyspray.php
When memory_limit or post_max_size or upload_max_filesize is set to unlimited value size doesn't be used for the computation of the attachments max size -  so if the three variable are set to -1 (unlimited) there are no attachment allowed but config allow them so in these case we could set value to a big number (php_int_max).
=> Flyspray max file size for attachments

themes/CleanFS/templates/details.tabs.comment.tpl
Notifications body contains an anchor #comment1 when a comment has been added.
ie: https://hostname/index.php?do=details&task_id=1#comment1
This patch adds the id attribute related to this anchor.
=> Add attribute id for each comment

themes/CleanFS/templates/index.tpl
When a page is loaded and mouse is hover a #tasklist tr, function Show is called (onmouseover).
Without a onmousemove event, the preview position is{top:10,left:10} which prints the div#desc_task_id at the top left of the window. It catches eye on this part of the window and disturbs. 
To reproduce this, put your cursor on a task and press F5 (Iceweasel, a little mouse move is needed on Chromium) .
There are several workarounds for this, but a simple and robust way to avoid that is to stop Show function before showing the div when cY=0.
=> Fix hover preview behaviour

themes/CleanFS/templates/links.tpl
When a search is done (tasklist context) and $_GET['dev'] is not empty, the tab "mytask" is highlighted whatever be the dev value.
When a search is done (tasklist context) and $_GET['dev'] is empty, no tab is highlighted.
With that patch, 
the tab "mytask" is highlighted only when $_GET['dev'] == $user->id. (not username)
Otherwise, for tasklist context, this is "tasklist" tab which is highlighted.
=> Change tabs highlighting

includes/class.flyspray.php, includes/modify.inc.php, index.php, scripts/details.php, themes/CleanFS/templates/details.edit.tpl
This patch avoids setting invalid list values by:
- constructed requests by authorized, but bad users.
- accidently setting invalid list values when moving a task to different project by authorized users.
Not perfect and finished the task-to-different-project user interactions/messages, but better than before and fixes sec issue.
=> task value checks

themes/CleanFS/templates/pm.groups.tpl
'isglobalgroup' does not exist in string translation file, but 'globalgroup' is. Maybe it could be good to reuse it ?
=> Reuse a string translation

themes/CleanFS/templates/pm.groups.tpl, themes/CleanFS/theme.css
There are a few project wide permission settings that overrule similiar group permission settings.
This patch makes this overruling visible on the group permissions page of a project to reduce the probability of a misconfiguration.
=> Show project overruling group settings

includes/modify.inc.php
- Trying to add an user with a bad email (such as "test") throws the following swift exception: 
```
Completely unexpected exception: Address in mailbox given [test] does not comply with RFC 2822, 3.6.2.
This should never happend, please inform Flyspray Developers
```
- Updating a user with a bad email format from admin & myprofile should not be allowed
This patch fixes both.
=> Add email format control

themes/CleanFS/templates/pm.groups.tpl
With a large definition (more than 1280) and default group definitions (6 columns), the table does not stay left align. It aligns with the line above (forms and buttons).
Adding a `display:block` enforces its left alignment.
```GET /index.php?project=1&do=pm&area=groups```
=> Fix table position

themes/CleanFS/templates/footer.tpl
* I think it prevents adoptation of the Flyspray.
* And I also think it prevents peoples from contributing/volunteering in Flyspray development. Flyspray was and is developed since 15 years by many people from over the world. An exclusive linking to one company url is not appropriate for a software developed by so many volunteers, beside there was/is not any sponsoring or code contribution for at least 1 year.
=> remove of exclusive sponsor link from footer

themes/CleanFS/templates/index.tpl
This effect will never apply and issues an error when viewing a list of tasks.
```GET /index.php?project=1&do=tasklist```
=> Fix a JS error

scripts/index.php
This notice occurred when class name is set to NULL for a tag (list_tag table).
```GET https://bugs.flyspray.org/index.php?project=0&do=index```
=> Fix a notice

includes/class.database.php, setup/index.php
Problem should be handled by adodb library in future, but until this fix can workaround the problem of missing socket parameter of the Connect() method.
german webhoster 1und1 uses localhost:/tmp/mysql5.sock for instance for their managed servers.
=> enable also mysqli db socket usage (quickfix)

htaccess.dist
Fixes a problem if url-rewriting is activated. 'My assigned tasks' is now navigable again in a specific project.
=> Typo in url-rewriting

js/tabs.js, themes/CleanFS/theme.css
e.g. enables tab styling like showing comments  on task details page side-by-side with task description on wide desktop screens, but below on smaller screens - without touching the current template files.
=> fix current js-tabs for css mediaqueries

includes/modify.inc.php
Fixes page redirect after admin edits a user profile. After update, FS returns to selected user profile instead of the admin user profile.
Closes FS#2136 (https://bugs.flyspray.org)
=> Fix page redirect after admin updates user info

js/callbacks/quickedit.php
task_priority are 1 to 6 (Defer to Very high) whereas task_severity are 1 to 5, so, checks should be separated
=> Fix task_priority pattern

includes/class.flyspray.php
The current possible values for config param passwdcrypt 'md5', 'sha1' and 'sha512' are unsalted hashing methods.
They should not be used for hashing passwords.
It does NOT mean that they are config parameters for the crypt() function! For that there are the constants CRYPT_MD5, CRYPT_BLOWFISH, CRYPT_SHA512, ... see http://php.net/manual/en/function.crypt.php
Future: Maybe setting 'passwdcrypt' config value will be deprecated or removed and other config names are set that are not so ambiguous. This will not effect existing oldtype stored password hashes, they are detected by their typical stored character length.
Future: Maybe the hashes get automatically converted to stronger/modern methods when the user logs in the next time and provides the raw password to Flyspray.
=> use hash_equals and a note to avoid unsalted hashing methods

includes/class.backend.php
GREATEST() function returns NULL if any argument is NULL (for MySQL only, not for Postgresql)
So, if there is no comment added for a task, a GREATEST(comment.date_added, task.date_opened, task.date_closed, task.last_edited_time) comparison will always return NULL.
The result can be seen in the column "Last edited" which is 'sometimes' empty because the function `tpl_draw_cell` from scripts/index.php:235 `$value = formatDate($task[$indexes[$colname]]);` with a 
`$task['max_date']` as NULL renders an empty string.
Sorting through the latest issue date is also affected.
A way to fix that is to replace the NULL output by 0 with a COALESCE function. 
Above, you can find an out-of-the-fs-box test case:
> Assuming you have fs_comments and fs_tasks tables (prefix=fs_)
``` sql
SELECT 
GREATEST( …
```
=> Fix empty last edited date and ordering by max_date

js/tabs.js
Changed add/remove of active class on tabs to be more explicit, which is safer for themes that may have added other classes to tabs (ie, FontAwesome).
=> Active tab class switching

includes/class.tpl.php
This fallback is used when calling 2 functions:
- tpl_userselect
- tpl_double_select
They are creating a new FsTpl instance without setting the theme.
Setting the $proj->prefs['theme_style'] in these 2 functions would make this hardcoded theming part useless.
`GET /index.php?project=1&do=pm&area=prefs`
=> Fix hardcoded theming fallback

scripts/index.php
and build the appropriate .csv filename also for the 'all projects' tasklist when doing csv export from a task search.
=> fix FS#2330

includes/class.flyspray.php
$val initially contains either an integer, or a string like 128M or 512K.
Therefore, to obtain the value in octets we need to
1) get the last character and store it
2) trim it from $val to get a correct number
3) multiply $val by the amount obtained through the switch control
That's what the patch does.
=> fix a PHP7.1 notice: A non well formed numeric value encountered ..

includes/constants.inc.php, js/callbacks/gethistory.php, js/callbacks/getsearches.php, js/callbacks/quickedit.php, js/callbacks/testemail.php
fixing $baseurl after including the header.php is too late, because some depending constants are effected by them (DOKU_BASE) too, that are set earlier. example: image url for dokuwiki smileys in the gethistory callback.
=> set baseurl early for js callbacks

plugins/dokuwiki/inc/HTTPClient.php
I get Error on install/upgrade
PHP Fatal error:  Cannot redeclare class DokuHTTPClient in [flyspray/plugins/dokuwiki/inc/HTTPClient.php](https://github.com/Flyspray/flyspray/blob/master/plugins/dokuwiki/inc/HTTPClient.php) on line 20
If I change the order of the classes, everything is working.
See also [Flyspray FS#2088](https://bugs.flyspray.org/index.php?do=details&task_id=2088)
with the same problem.
System: Apache2.4, PHP5.6
=> Error in HTTPClient.php on install/upgrade

scripts/index.php
PHP's implementation of fputcsv() fails to properly escape CSV quote
characters preceeded by a backslash. An input string like `test \" test`
is converted to `"test \" test"` instead of the expected `"test \"" test"`
result.
Due to this issue, it is impossible to properly parse the generated
task CSV export list.
Work around the problem by utilizing a custom CSV formatting function
instead which properly escapes quote characters.
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
=> index.php: workaround PHP bug 43225

themes/CleanFS/templates/lostpw.step1.tpl
usernames up to 32 chars allowed, so it should be possible for that users to use the password forgotten functionality. :-)
=> fix FS#2490 lostpw for long usernames

includes/class.database.php
If you try to open the detailed view of a non existing ticket with PHP >= 7.2.x by changing the ID by hand, a non-countable warning occurs (http://php.net/manual/en/migration72.incompatible.php). This fix should handle that.
=> Fix for error using a non existing ticket ID

themes/CleanFS/templates/common.datepicker.tpl, themes/CleanFS/templates/index.tpl, themes/CleanFS/theme.css
When working with the advanced task search, a yet existing value from a previous search in a text input field can be quickly overseen and the user may wonder why the search result is smaller than expected. By highlighting that text input fields the user immediately sees the filled search criteria. (when the advanced search form is visible, ok ..)
=> highlight advanced search input fields

themes/CleanFS/templates/header.tpl
avoid a js error in details.js if a task is not accessible for a user/guest. Doesn't help on 'mark_private' tasks.
Future: Flyspray should know a bit more about the current $task **before** header.tpl is rendered.
=> temp js fix

includes/class.backend.php, includes/class.flyspray.php, includes/class.tpl.php, scripts/index.php, themes/CleanFS/templates/common.list.tpl, themes/CleanFS/templates/details.view.tpl
In most cases it is sufficient just to set a background-color for a tag, no need to fiddle with theme css file. Font color is automatically calculated to ensure good contrast.
Also a new template function tpl_tag($tag_id) introduced.
new function getAllTags() is called only when required, maximum once per request. It simplifies the  get_task_list sql query built for getting a tasklist and also fixes bug with tag styles mixed.
=> simple set a color for a tag

themes/CleanFS/templates/common.list.tpl
instead of showing them with disabled attribute. This in preparation of merge feature FS#1791 to keep the UI simple
Also use named RESOLUTION_DUPLICATE in template
=> don't show delete checkboxes under some conditions

scripts/details.php, themes/CleanFS/templates/details.edit.tpl
Allows a user who wants to move a task to another project to choose legal entries for the task properties.
fixes FS#2134
=> fix FS#2134 adapt selects when moving task to other project

.gitignore
I saw that there's still a rule for the old PHPEdit so I thought it'd be useful to add relevant rules for VSCode not only because I use it myself but also because it's quite popular right now.
Rules taken from the "official" repository: https://github.com/github/gitignore
=> Added rules for Visual Studio Code

themes/CleanFS/templates/header.tpl, themes/CleanFS/theme.css
When on smaller screens the horizontal project menu, project selector and quicktaskidsearch do not fit on one line, the project selector overflows in Flyspray 1.0 CleanFS theme. Due the css float cleared too late, the content div overlapped and the project selector was not clickable with mouse.
=> fix overflowing projectselector not clickable

includes/class.backend.php, includes/class.flyspray.php, scripts/authenticate.php
Changes:
* config parameter to set authentication method
* configurable LDAP authentication
* account provisionning from LDAP on first login
* fallback to native authentication if LDAP user not found
To configure LDAP authentication, set following parameters in config file
(flyspray.conf.php):
```
[general]
auth_method = 'ldap'
[ldap]
host = 'ldap.example.com'
port = '389'
version = '3'
base_dn = 'ou=users,dc=example,dc=com'
search_user = 'your_bind_dn'
search_pass = 'your_bind_password'
filter = 'uid=%USERNAME%'
field_name = 'cn'
field_email = 'mail'
```
=> feat: make ldap configurable

plugins/dokuwiki/dokuwiki_formattext.inc.php
before switching back to flyspray global $conf
some dokuwiki $conf custom settings are required when compiling html output, like their relnofollow setting.
(workaround)
=> use dokuwiki $conf until full rendered

plugins/dokuwiki/dokuwiki_formattext.inc.php
- deactivated some seldom used or redundant buttons on the dokuwikitoolbar (1 instead 3 for adding links)
- made the toolbar a bit more flexible to customize
- made texts of the toolbar translatable
- added an idea for having a simple dokuwikicheatsheet when you need it, simply by hovering an "i"nfo-button on the toolbar
=> review dokuwikitoolbar and a wiki-cheatsheet

scripts/activity.php
Use svg as fallback when gd extension is not installed.
But maybe replace the sparkline image generation in future completely as svg is more flexible to use ...
... and travis-ci still does not like the dependency to jamiebicknell/Sparkline ...
=> svg activity sparklines

plugins/dokuwiki/inc/parser/xhtml.php
Flyspray does not use SimplePie and so has no FeedParser.php. So return before it even tries to require_once() that file as quick fix.
=> fix an error when dokuwiki rss syntax feature tried

themes/CleanFS/templates/index.tpl
The default CleanFS theme loads also the task description of each task in a tasklist and only a mouse hover a task summary shows the description preview of a task. This feature has impact on required php workload and those descriptions are not used in most cases and also effects page size for each tasklist view. As compromise this change loads only the task description for maximal first 25 rows of a tasklist.
=> limit preload task description on long tasklists (default theme)

includes/class.backend.php
Flyspray has a hidden/undocumented feature since 2006 by using the + char in the search string for more narrow search conditions.
But if the + is at end of a search word, the replacement is unwanted/unneeded and a search string like 'memtest86+' searched for 'memtest86 ' (with the space at end) so would not find 'memtest86+'. This patch takes care of it.
=> fix FS#2591 not replace + at end of a search word

includes/class.tpl.php
Current PHP 8.0.2 throws an error with get_class_methods() if the class not exists instead of return null and documented currently on php.net
So lets test first with class_exists()
=> get_class_methods() PHP8 changes

js/callbacks/getusage.php, themes/CleanFS/templates/getusage.callback.tpl
for quick view/hover in admin or project manager area to see where a tag/category/list_* id is used. Only up to 10 task titles are loaded and shown is planned.
It's an alternative to using the normal tasklist filters, but for full handling/mass operation the normal tasklist is still necessary.
=> get usage stub

setup/index.php
The check in `setup/index.php` contains a variable `pass_phrase` which is no where else used.
Hence this suggestion to remove.
=> remove unused pass_phrase variable

plugins/dokuwiki/dokuwiki_formattext.inc.php
When a dokuwiki syntax text is not yet cached in the DB, it parses the text.
The config for dokuwiki syntax was not loaded yet there resulting in a warning in php 8.
=> load dokuwiki config earlier before writing a cache entry to db, fixes warning GH#817

tests/createTestData.php
makes it easier to apply some testdata to an existing sql backup/dump that has more than only the first task.
=> autodetect next taskid for createTestData

includes/class.notify.php, includes/i18n.inc.php, includes/modify.inc.php, themes/CleanFS/templates/common.profile.tpl, themes/CleanFS/templates/pm.prefs.tpl
allows user sets their language to 'project', meaning using the language setting of the project instead of fixed own defined one.
Projects can set their own language, but now also allows setting to 'global', which means the global Flyspray language setting is used.
=> optional autofallback language settings

includes/class.notify.php
- keep http:// or https:// in detected links visible for html body of notification emails
- also ignore replacing links when a single quotation mark before the link is detected, not only double quotation mark, assuming it is part of an html tag attribute.
(https://www.w3.org/TR/html401/intro/sgmltut.html#h-3.2.2 or https://html.spec.whatwg.org/#attributes-2)
=> keep protocol visible in emails

includes/modify.inc.php, scripts/admin.php, themes/CleanFS/templates/admin.checks.tpl
offer ability to delete old unsent xmpp messages so when reestablishing xmpp in a flyspray install it doesn't run amok/flood.
=> xmpp unsent messages cleanup

themes/CleanFS/templates/common.cat.tpl
The way categories are managed in Flyspray might hit the max_input_vars PHP ini setting for big category trees. For a default 1000 max_input_vars in PHP ini settings the limit of categories in worst case is 166 categories in a project or the global cat tree. (up to 6 vars  per category entry) 
Without any delete category option selected the default category limit per project is 199 (5*199+4=999) for the default 1000 max_input_vars limit.
This shows a warning if this limit is reached and suggest increasing max_input_vars in PHP in this case.
=> show warning if max_input_vars is too low for big category trees

README.md
travis-ci is not used anymore by this repository, so removed the outdated badge image link.
Also www.flyspray.org is back on track again.
bugs.flyspray.org is not yet restored (but will), so https://github.com/flyspray/flyspray/issues meanwhile.
=> remove unused travis-badge, flyspray.org domain alive

includes/class.gpc.php, lang/es.php, setup/index.php, setup/upgrade.php
Some former developer had personal mail addresses for flyspray.org-domain on old hosting.
Not setup on new hosting.
=> Mail address cleanup

setup/templates/pre_install.tpl
Some minimal linux distros do not install/enable the ctype extension on php install.
So lets add a check here.
=> preinstall check if ctype extension is enabled

includes/modify.inc.php
Since 1.0-rc11 Post::val() is not used for arrays anymore.
Instead each php snippet/function doing changes to the db must do their own custom checks if the sent form matches expected data format.
=> remove related tasks fix regression of 1.0-rc11

themes/CleanFS/templates/pm.prefs.tpl
In themes/CleanFS/templates/pm.prefs.tpl:
Remove third parameter ($labelIsValue) from tpl_options() on line 105.
This makes the <select> render with version_id as option values.
Version ID is then stored in {projects}.default_due_version, which allows the "Due In Version" <select> in newtask to render as expected.
=> Flyspray/Flyspray #879

includes/modify.inc.php, scripts/newtask.php, themes/CleanFS/templates/newtask.tpl
Allow new tasks to be added in sequence by non-anonymous users.
In scripts/newtask.php:
Add a boolean value "addanothertask" to template data.  If the user is logged in and the checkbox was previously checked, this state is carried to the next new task via $_SESSION['addanothertask'].
If present, previously set session flag is cleared.
In themes/CleanFS/templates/newtask.tpl:
Add a checkbox "addanothertask", only visible to logged-in users.
In includes/modify.in.php, case "newtask.newtask":
If the "addanothertask" checkbox was not checked, redirect to task details as before.
Otherwise, set $_SESSION['addanothertask'] = 1 and redirect back to newtask.
On error, clear the session flag to prevent it from lingering.
=> Flyspray/Flyspray #880

includes/class.database.php, includes/constants.inc.php
Before it was check only if DEBUG_SQL was defined or not to enable debug mode. Now this setting supports different values.
Beside setting true/false allows setting DEBUG_SQL to the special ADOdb values -1, 99, and -99.
=> false/true of DEBUG_SQL constant instead just defined()

plugins/dokuwiki/inc/parser/parser.php
when dokuwiki syntax is used
fixes #825
=> allow detecting [ and ] as part of URL for externallink parser mode

includes/class.tpl.php
when something looks like a FS#xxx Flyspray task in comments or task descriptions, but does not exists, then catch that and do not try to build a link to nowhere.
=> format of nonexistent tasks

includes/class.flyspray.php
In Flyspray::listUsers():
Instantiate SQL clause variables as empty strings, just in case.
When stats is selected, do not overwrite $orderby.
=> Flyspray/Flyspray #901: Bulk User Edit Sorting
